requestError = "requestError"
requestLogin = "requestLogin"
requestRegister = "requestRegister"
requestRank = "requestRank"
requestLogout = "requestLogout"
requestUploadRecord = "requestUploadRecord"

responseLogin = "responseLogin"
responseRegister = "responseRegister"
responseRank = "responseRank"
responseLogout = "responseLogout"
responseUploadRecord = "responseUploadRecord"
